version: "3.8"

volumes:
  rabbitmq_data:

services:
  # order: 
  #   image: mongo

  ####################################
  # RabbitMQ: The messaging broker   
  ####################################
  rabbitmq:
    image: rabbitmq:3-management
    hostname: esd-rabbit
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes: 
      - rabbitmq_data:/var/lib/rabbitmq

  ####################################
  # twilio_notifs: The twilio notifier
  ####################################
  twilio_notifs:
    build:
      context: ./
      dockerfile: twilio_notifs.Dockerfile
    image: tinggzster/twilio_notifs:esd
    restart: always
    depends_on:
      - rabbitmq
    environment:
      rabbit_host: rabbitmq
      rabbit_port: 5672
      PYTHONUNBUFFERED: 1

    # hostname: esd-twilio
    # restart: always
    # ports:
    #   - "80:80"
    # volumes:
    #   - twilio_data:/var/lib/twilio
    # environment:
    #   - TWILIO_ACCOUNT_SID={{.TwilioAccountSid}}
    #   - TWILIO_AUTH_TOKEN={{.TwilioAuthToken}}
    #   - TWILIO_NUMBER={{.TwilioNumber}}
    #   - TWILIO_NOTIF_URL={{.TwilioNotifUrl}}
    #   - TWILIO_NOTIF_SID={{.TwilioNotifSid}}
    #   - TWILIO_NOTIF_TOKEN={{.TwilioNotifToken}}
    #   - TWILIO_NOTIF_FROM={{.TwilioNotifFrom}}
    #   - TWILIO_NOTIF_TO={{.TwilioNotifTo}}
    #   - TWILIO_NOTIF_SUBJECT={{.TwilioNotifSubject}}
    #   - TWILIO_NOTIF_BODY={{.TwilioNotifBody}}
    #   - TWILIO_NOTIF_SMS_BODY={{.TwilioNotifSmsBody}}
    #   - TWILIO_NOTIF_SMS_FROM={{.TwilioNotifSmsFrom}}
    #   - TWILIO_NOTIF_SMS_TO={{.TwilioNotifSmsTo}}
    #   - TWILIO_NOTIF_SMS_SID={{.TwilioNotifSmsSid}}
    #   - TWILIO_NOTIF_SMS_TOKEN={{.TwilioNotifSmsToken}}
    #   - TWILIO_NOTIF_SMS_FROM={{.TwilioNotifSmsFrom}}
    #   - TWILIO_NOTIF_SMS_TO={{.TwilioNotifSmsTo}}
    #   - TWILIO_NOTIF_SMS_SID={{.TwilioNotifSms


  ###################################
  # error: The Error microservice
  ###################################
  error:
    build:
      context: ./
      dockerfile: error.Dockerfile
    image: tinggzster/error:esd
    restart: always
    depends_on:
      - rabbitmq
    environment:
      rabbit_host: rabbitmq
      rabbit_port: 5672
      PYTHONUNBUFFERED: 1

  ###################################
  #item microservice: The Item microservice
  ###################################

  item:
    build:
      context: ./
      dockerfile: item.Dockerfile
    image: tinggzster/item:esd
    restart: always
    environment:
      dbURI: mongodb+srv://esdt4:esdt4@nodejstutoriallearning.xssjk.mongodb.net/itemdb?retryWrites=true&w=majority
    ports:
      - "5000:5000"

  ###################################
  #profile microservice: The Item microservice
  ###################################

  profile:
    build:
      context: ./
      dockerfile: profile.Dockerfile
    image: tinggzster/profile:esd
    restart: always
    environment:
      dbURL: mysql+mysqlconnector://root@localhost:3306/profile
      PYTHONUNBUFFERED: 1
    ports:
      - "5001:5001"

  ###################################
  #Accept Offer: The Accept Offer complex microservice
  ###################################

  accept_offer:
    build:
      context: ./
      dockerfile: accept_offer.Dockerfile
    image: tinggzster/accept_offer:esd
    restart: always
    depends_on:
      - rabbitmq
      - item
      - error
      - twilio_notifs 
    environment:
      rabbit_host: rabbitmq
      rabbit_port: 5672
      PYTHONUNBUFFERED: 1
      item_URL: http://item:5001/item
      profile_URL: http://profile:5000/profile
    ports:
      - "5300:5300"

  ###################################
  #Create Listing: The Create Listing complex microservice
  ###################################
  create_listing:
    build:
      context: ./
      dockerfile: create_listing.Dockerfile
    image: tinggzster/create_listing:esd
    restart: always
    depends_on:
      - rabbitmq
      - item
      - error
      - twilio_notifs 
    environment:
      rabbit_host: rabbitmq
      rabbit_port: 5672
      PYTHONUNBUFFERED: 1
      item_URL: http://item:5001/item
      profile_URL: http://profile:5000/profile
    ports:
      - "5100:5100" 


  ###################################
  #Make Offer: The Make Offer complex microservice
  ###################################

  make_offer: 
    build:
      context: ./
      dockerfile: make_offer.Dockerfile
    image: tinggzster/make_offer:esd
    restart: always
    depends_on:
      - rabbitmq
      - twilio_notifs
      - error
      - item
      - profile
    environment:
      rabbit_host: rabbitmq
      rabbit_port: 5672
      PYTHONUNBUFFERED: 1
      item_URL: http://item:5001/item
      profile_URL: http://profile:5000/profile
    ports:
      - "5200:5200" 


  ###################################
  #leave_rating: The leave rating complex microservice
  ###################################

  leave_rating:
    build:
      context: ./
      dockerfile: leave_rating.Dockerfile
    image: tinggzster/leave_rating:esd
    restart: always
    depends_on:
      - rabbitmq
      - error
      - profile
    environment:
      rabbit_host: rabbitmq
      rabbit_port: 5672
      PYTHONUNBUFFERED: 1
      profile_URL: http://profile:5000/profile
    ports:
      - "5500:5500" 

  ###################################
  #Reject Offer: The Reject Offer complex microservice
  ###################################

  reject_offer:
    build:
      context: ./
      dockerfile: reject_offer.Dockerfile
    image: tinggzster/reject_offer:esd
    restart: always
    depends_on:
      - rabbitmq
      - error
      - twilio_notifs
      - profile
      - item
    environment:
      rabbit_host: rabbitmq
      rabbit_port: 5672
      PYTHONUNBUFFERED: 1
      item_URL: http://item:5001/item
      profile_URL: http://profile:5000/profile
    ports:
      - "5400:5400"

  ###################################
  #Remove Offer: The RemoveOffer complex microservice
  ################################### 

  remove_offer:
    build:
      context: ./
      dockerfile: remove_offer.Dockerfile
    image: tinggzster/remove_offer:esd
    restart: always
    depends_on:
      - rabbitmq
      - error
      - twilio_notifs
      - profile
      - item
    environment:
      rabbit_host: rabbitmq
      rabbit_port: 5672
      PYTHONUNBUFFERED: 1
      item_URL: http://item:5001/item
      profile_URL: http://profile:5000/profile
    ports:
      - "5600:5600"



  

