version: "3.8"

volumes:
  rabbitmq_data:
  # pgdata: 
  # kongadata:

services:
  # order: 
  #   image: mongo

  ####################################
  # RabbitMQ: The messaging broker   
  ####################################
  rabbitmq:
    image: rabbitmq:3-management
    hostname: esd-rabbit
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes: 
      - rabbitmq_data:/var/lib/rabbitmq

  ####################################
  # twilio_notifs: The twilio notifier
  ####################################
  twilio_notifs:
    build:
      context: ./notifications
      dockerfile: twilio_notifs.Dockerfile
    image: tinggzster/twilio_notifs:esd
    restart: always
    depends_on:
      - rabbitmq
    environment:
      rabbit_host: rabbitmq
      rabbit_port: 5672
      PYTHONUNBUFFERED: 1
    env_file:
      - .env

  ###################################
  # error: The Error microservice
  ###################################
  error:
    build:
      context: ./error
      dockerfile: error.Dockerfile
    image: tinggzster/error:esd
    restart: always
    depends_on:
      - rabbitmq
    environment:
      rabbit_host: rabbitmq
      rabbit_port: 5672
      PYTHONUNBUFFERED: 1
      dbURI: mongodb+srv://tingz:C1e3RbVUrvmAkDzl@wtesd.azs8r.mongodb.net/ESDnotifs?retryWrites=true&w=majority

  ###################################
  #profile microservice: The Profile microservice
  ###################################

  profile:
    build:
      context: ./profile
      dockerfile: profile.Dockerfile
    image: tinggzster/profile:esd
    restart: always
    environment:
      dbURL: mysql+mysqlconnector://ESDT4@host.docker.internal:3306/profile
      PYTHONUNBUFFERED: 1
    ports:
      - "5000:5000"

  ###################################
  #item microservice: The Item microservice
  ###################################

  item:
    build:
      context: ./item
      dockerfile: item.Dockerfile
    image: tinggzster/item:esd
    restart: always
    environment:
      dbURI: mongodb+srv://esdt4:esdt4@nodejstutoriallearning.xssjk.mongodb.net/itemdb?retryWrites=true&w=majority
    ports:
      - "5001:5001"


  ###################################
  #Create Listing: The Create Listing complex microservice
  ###################################
  create_listing:
    build:
      context: ./complex
      dockerfile: create_listing.Dockerfile
    image: tinggzster/create_listing:esd
    restart: always
    depends_on:
      - item
      - profile
    environment:
      PYTHONUNBUFFERED: 1
      create_item_URL: http://item:5001/createitem
      profile_URL: http://profile:5000/profile/
    ports:
      - "5100:5100" 


  ###################################
  #Make Offer: The Make Offer complex microservice
  ###################################

  make_offer: 
    build:
      context: ./complex
      dockerfile: make_offer.Dockerfile
    image: tinggzster/make_offer:esd
    restart: always
    depends_on:
      - rabbitmq
      - twilio_notifs
      - error
      - item
      - profile
    environment:
      rabbit_host: rabbitmq
      rabbit_port: 5672
      PYTHONUNBUFFERED: 1
      item_URL: http://item:5001/items/
      profile_URL: http://profile:5000/profile/
    ports:
      - "5200:5200" 


  ###################################
  #Accept Offer: The Accept Offer complex microservice
  ###################################

  accept_offer:
    build:
      context: ./complex
      dockerfile: accept_offer.Dockerfile
    image: tinggzster/accept_offer:esd
    restart: always
    depends_on:
      - rabbitmq
      - item
      - error
      - twilio_notifs 
    environment:
      rabbit_host: rabbitmq
      rabbit_port: 5672
      PYTHONUNBUFFERED: 1
      item_URL: http://item:5001/items/
    ports:
      - "5300:5300"

  ###################################
  #Reject Offer: The Reject Offer complex microservice
  ###################################

  reject_offer:
    build:
      context: ./complex
      dockerfile: reject_offer.Dockerfile
    image: tinggzster/reject_offer:esd
    restart: always
    depends_on:
      - rabbitmq
      - error
      - twilio_notifs
      - item
    environment:
      rabbit_host: rabbitmq
      rabbit_port: 5672
      PYTHONUNBUFFERED: 1
      item_URL: http://item:5001/items/
    ports:
      - "5400:5400"

  ###################################
  #leave_rating: The leave rating complex microservice
  ###################################

  leave_rating:
    build:
      context: ./complex
      dockerfile: leave_rating.Dockerfile
    image: tinggzster/leave_rating:esd
    restart: always
    depends_on:
      - profile
      - item
    environment:
      PYTHONUNBUFFERED: 1
      rate_profile_URL: http://profile:5000/profile/ratings/
      item_URL: http://item:5001/items/
    ports:
      - "5500:5500" 

  ###################################
  #Remove Offer: The RemoveOffer complex microservice
  ################################### 

  remove_offer:
    build:
      context: ./complex
      dockerfile: remove_offer.Dockerfile
    image: tinggzster/remove_offer:esd
    restart: always
    depends_on:
      - profile
      - item
    environment:
      PYTHONUNBUFFERED: 1
      item_URL: http://item:5001/items/
      profile_URL: http://profile:5000/profile/
    ports:
      - "5600:5600"
